"""Add email column to users table

Revision ID: 13edca21c2f1
Revises: 2653352ad1a3
Create Date: 2025-01-07 20:19:03.578528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13edca21c2f1'
down_revision: Union[str, None] = '2653352ad1a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('celery_tasks', sa.Column('file_unique_name', sa.String(length=40), nullable=False))
    op.drop_constraint('celery_tasks_file_name_key', 'celery_tasks', type_='unique')
    op.create_unique_constraint(None, 'celery_tasks', ['file_unique_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'celery_tasks', type_='unique')
    op.create_unique_constraint('celery_tasks_file_name_key', 'celery_tasks', ['file_name'])
    op.drop_column('celery_tasks', 'file_unique_name')
    # ### end Alembic commands ###
