"""Add email column to users table

Revision ID: 1ee4b1e9e7bc
Revises: 13edca21c2f1
Create Date: 2025-01-07 20:44:44.856271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ee4b1e9e7bc'
down_revision: Union[str, None] = '13edca21c2f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
