"""change the schema

Revision ID: 21a43b7a1501
Revises: 1ee4b1e9e7bc
Create Date: 2025-01-07 21:23:51.515284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21a43b7a1501'
down_revision: Union[str, None] = '1ee4b1e9e7bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('celery_sub_tasks', sa.Column('task_group_id', sa.Integer(), nullable=False))
    op.add_column('celery_sub_tasks', sa.Column('sub_task_internal_id', sa.String(length=40), nullable=False))
    op.create_unique_constraint(None, 'celery_sub_tasks', ['sub_task_internal_id'])
    op.drop_constraint('celery_sub_tasks_task_id_fkey', 'celery_sub_tasks', type_='foreignkey')
    op.create_foreign_key(None, 'celery_sub_tasks', 'celery_tasks', ['task_group_id'], ['id'], ondelete='CASCADE')
    op.drop_column('celery_sub_tasks', 'task_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('celery_sub_tasks', sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'celery_sub_tasks', type_='foreignkey')
    op.create_foreign_key('celery_sub_tasks_task_id_fkey', 'celery_sub_tasks', 'celery_tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'celery_sub_tasks', type_='unique')
    op.drop_column('celery_sub_tasks', 'sub_task_internal_id')
    op.drop_column('celery_sub_tasks', 'task_group_id')
    # ### end Alembic commands ###
