"""last_schema

Revision ID: 2220fb43bbfc
Revises: 5bb2a7b8e2b7
Create Date: 2025-01-13 20:28:14.064245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2220fb43bbfc'
down_revision: Union[str, None] = '5bb2a7b8e2b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('celery_tasks', sa.Column('file_type', sa.String(length=25), nullable=False))
    op.drop_column('celery_tasks', 'task_type')
    op.drop_column('celery_tasks', 'file_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('celery_tasks', sa.Column('file_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('celery_tasks', sa.Column('task_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_column('celery_tasks', 'file_type')
    # ### end Alembic commands ###
