"""initial

Revision ID: 2653352ad1a3
Revises: 
Create Date: 2025-01-07 11:22:33.570210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2653352ad1a3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('celery_tasks',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(length=40), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('total_sub_tasks', sa.Integer(), nullable=False),
    sa.Column('remaining_sub_tasks', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_name')
    )
    op.create_index(op.f('ix_celery_tasks_id'), 'celery_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_celery_tasks_uid'), 'celery_tasks', ['uid'], unique=True)
    op.create_table('celery_sub_tasks',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['celery_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_celery_sub_tasks_id'), 'celery_sub_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_celery_sub_tasks_uid'), 'celery_sub_tasks', ['uid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_celery_sub_tasks_uid'), table_name='celery_sub_tasks')
    op.drop_index(op.f('ix_celery_sub_tasks_id'), table_name='celery_sub_tasks')
    op.drop_table('celery_sub_tasks')
    op.drop_index(op.f('ix_celery_tasks_uid'), table_name='celery_tasks')
    op.drop_index(op.f('ix_celery_tasks_id'), table_name='celery_tasks')
    op.drop_table('celery_tasks')
    # ### end Alembic commands ###
