"""ending

Revision ID: 303739c94df9
Revises: 96f57fbc0d00
Create Date: 2025-01-15 07:28:54.720083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '303739c94df9'
down_revision: Union[str, None] = '96f57fbc0d00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('celery_tasks', 'file_path',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('celery_tasks', 'progress',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('celery_tasks', 'total_sub_tasks',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('celery_tasks', 'remaining_sub_tasks',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('celery_tasks', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('celery_tasks', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('celery_tasks', 'remaining_sub_tasks',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('celery_tasks', 'total_sub_tasks',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('celery_tasks', 'progress',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('celery_tasks', 'file_path',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
