"""final main schema

Revision ID: 5bb2a7b8e2b7
Revises: 3f6acac44b6f
Create Date: 2025-01-13 19:57:04.133224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bb2a7b8e2b7'
down_revision: Union[str, None] = '3f6acac44b6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('celery_tasks', sa.Column('task_type', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('celery_tasks', 'task_type')
    # ### end Alembic commands ###
