"""db final

Revision ID: 96f57fbc0d00
Revises: 2220fb43bbfc
Create Date: 2025-01-15 06:36:12.452267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96f57fbc0d00'
down_revision: Union[str, None] = '2220fb43bbfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_celery_sub_tasks_id', table_name='celery_sub_tasks')
    op.drop_index('ix_celery_tasks_id', table_name='celery_tasks')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_celery_tasks_id', 'celery_tasks', ['id'], unique=False)
    op.create_index('ix_celery_sub_tasks_id', 'celery_sub_tasks', ['id'], unique=False)
    # ### end Alembic commands ###
