"""engni

Revision ID: a98020646581
Revises: 303739c94df9
Create Date: 2025-01-15 07:35:43.681441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a98020646581'
down_revision: Union[str, None] = '303739c94df9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('celery_tasks', 'file_unique_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('celery_tasks', 'main_task_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('celery_tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('celery_tasks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('celery_tasks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('celery_tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('celery_tasks', 'main_task_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('celery_tasks', 'file_unique_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
