"""change the schema

Revision ID: fd04df83876c
Revises: 21a43b7a1501
Create Date: 2025-01-07 21:33:46.039726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd04df83876c'
down_revision: Union[str, None] = '21a43b7a1501'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('celery_tasks', sa.Column('task_internal_id', sa.String(length=40), nullable=False))
    op.create_unique_constraint(None, 'celery_tasks', ['task_internal_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'celery_tasks', type_='unique')
    op.drop_column('celery_tasks', 'task_internal_id')
    # ### end Alembic commands ###
