services:
  fastapi-app:
    build: ./app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=celery
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres-db
      - POSTGRES_PORT=5432
      - REDIS_PORT=6379
      - REDIS_HOST=redis
    depends_on:
      - postgres-db
      - redis

  celery:
    build: ./app
    container_name: celery_worker

    command:  celery -A Background_task.file_task worker --loglevel=debug
    depends_on:
      - redis
      - postgres-db
      
  postgres-db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: celery
    
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "root"
    depends_on:
      - postgres-db

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    