services:

  alembic:
    build: .
    image: fastpi-alemic:v2
    env_file:
      - .env
    volumes:
      - .:/home/fastapi
    command:
      - /bin/sh
      - -c
      - |
        alembic upgrade head
    depends_on:
      - postgres
      - redis
      - fastapi
      

  fastapi:
    build: .
    image: fastpi-fastapi:v2
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/home/fastapi

  worker:
    build: .
    container_name: worker
    image: fastapi-celery:v2-celery
    volumes:
      - .:/home/fastapi
    env_file:
      - .env
    restart: on-failure
    command:  
      - /bin/sh
      - -c
      - |
        celery -A app.tasks.config worker --loglevel=info -c 10
    depends_on:
      - fastapi
      - redis

  beat:
    build: .
    container_name: beat
    image: fastapi-beat:v2-celery
    volumes:
      - .:/home/fastapi
    env_file:
      - .env
    restart: on-failure
    command:  
      - /bin/sh
      - -c
      - |
        celery -A app.tasks.config beat --loglevel=info
    depends_on:
      - fastapi
      - redis
      - worker

  flower:
    build: .
    container_name: flower
    image: fastapi-flower:v2-celery
    volumes:
      - .:/home/fastapi
    env_file:
      - .env
    restart: on-failure
    command:  
      - /bin/sh
      - -c
      - |
        celery -A app.tasks.config flower --loglevel=info --port=9090
    ports:
      - "9090:9090"
    depends_on:
      - fastapi
      - redis
      - worker

  postgres:
    image: postgres:15-alpine3.19
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin
  #   ports:
  #     - "5430:80"
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
  #     PGADMIN_DEFAULT_PASSWORD: "root"
  #   depends_on:
  #     - postgres-db

  redis:
    image: redis:alpine
    ports:
      - "6378:6379"

# Volumes for persistent data
volumes:
  postgres_data:
  redis_data:
