services:
  fastapi-app:
    build: ./app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=celery
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres-db
      - POSTGRES_PORT=5432
      - REDIS_PORT=6379
      - REDIS_HOST=redis
    depends_on:
      - postgres-db
      - redis
    volumes:
      - ./app:/app

  celery:
    build: ./app
    container_name: celery_worker
    command: celery -A Background_task.file_task worker -B --loglevel=debug
    depends_on:
      - redis
      - postgres-db
    volumes:
      - ./app:/app

  flower:
    build: ./app
    image: mher/flower
    container_name: celery_flower
    ports:
      - "5555:5555"
    command: celery -A Background_task.file_task.app flower
    environment:
      CELERY_BROKER_URL: redis://redis:6379
      CELERY_RESULT_BACKEND: db+postgresql://postgres:postgres@postgres-db:5432/celery
    depends_on:
      - celery
      - redis
      - postgres-db
      - fastapi-app
    volumes:
      - ./app:/app

  postgres-db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: celery
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "root"
    depends_on:
      - postgres-db

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

# Volumes for persistent data
volumes:
  postgres_data:
  redis_data:
